#!/usr/bin/python

#
#  erlenmeyer
#  Erlenmeyer
#
#  Created by Patrick Perini on February 5, 2013.
#  See readme.md for licensing information.
#

## FIXME
from libs import CoreData
import jinja2
from libs import jinja2_filters

cd = CoreData.CoreData('/Users/pcperini/Documents/Code/MegaBits/MegaBits Kit/MegaBits Kit/Models/MBModels.xcdatamodeld')
tE = jinja2.Environment(loader = jinja2.PackageLoader(__name__, 'templates'))

for filter in dir(jinja2_filters):
    if not filter.startswith('__'):
        tE.filters[filter] = getattr(jinja2_filters, filter)

template = tE.get_template('models/Model.tmpl.py')
file = open('/Users/pcperini/Desktop/Model.py', 'w')
file.write(template.render({
    "metadata": {},
    "model": {
        "primaryKey": "uuid"
    }
}))
file.close()

for model in cd['models']:
    template = tE.get_template('models/ModelObject.tmpl.py')
    file = open('/Users/pcperini/Desktop/models/%s.py' % (model['className']), 'w')
    file.write(template.render({
        "metadata": {},
        "model": model
    }))
    file.close()
    
    template = tE.get_template('handlers/ModelObjectHandler.tmpl.py')
    file = open('/Users/pcperini/Desktop/handlers/%sHandler.py' % (model['className']), 'w')
    file.write(template.render({
        "metadata": {},
        "model": model
    }))
    file.close()
## /////